#! /bin/python3

'''
说明：本脚本请设置可执行权限后，双击在终端运行，或者终端命令行`python3 reset_apt_sources.py`
版本：0.1
作者：Zz [loaden@gmail.com, QQ群：19346666]
'''

import os
import sys
import configparser


def get_auth():
    euid = os.geteuid()
    if euid != 0:
        args = ['sudo', sys.executable] + sys.argv + [os.environ]
        # replaces the currently-running process with the sudo
        os.execlpe('sudo', *args)
    return euid == 0


def user_agree_to_reset(src_file):
    msg = "源文件" + src_file + "已被修改，是否重置？(Y/n)"
    r = 'Y'
    while (r != 'y' and r != 'n' and r != ''):
        r = input(msg).lower()
    return r != 'n'


class SourcesBase():
    def __init__(self):
        self.os_version_file = '/etc/os-version'
        self.src_sources_list = '/etc/apt/sources.list'
        self.src_appstore_list = '/etc/apt/sources.list.d/appstore.list'
        self.src_printer_list = '/etc/apt/sources.list.d/printer.list'
        self.os_edition_name = ('Community', 'Home', 'Professional')
        self.os_edition = self.get_os_edition_name()

    def get_os_edition_name(self):
        try:
            cf = configparser.ConfigParser()
            cf.read(self.os_version_file)
        except FileNotFoundError:
            print("当前系统不是Deepin社区版、UOS专业版或个人版")
        else:
            return cf.get('Version', 'EditionName')

    def get_default_sources(self):
        try:
            with open(self.src_sources_list) as src:
                content = src.read()
        except FileNotFoundError:
            print(self.src_sources_list, "文件不存在")
        else:
            return content

    def default_sources_should_be(self):
        return ''

    def reset_default_sources(self):
        with open(self.src_sources_list, 'w') as src:
            src.write(self.default_sources_should_be())
            print(self.src_sources_list, "重置成功")


class DefaultSources(SourcesBase):
    def __init__(self):
        super().__init__()

    def default_sources_should_be(self):
        if (self.os_edition == self.os_edition_name[0]):
            return '## Generated by deepin-installer\n' \
                'deb [by-hash=force] https://community-packages.deepin.com/deepin/ apricot main contrib non-free\n' \
                '#deb-src https://community-packages.deepin.com/deepin/ apricot main contrib non-free\n'
        elif (self.os_edition == self.os_edition_name[1]):
            return '## Generated by deepin-installer\n' \
                'deb [by-hash=force] https://home-packages.chinauos.com/home plum main contrib non-free\n' \
                '#deb-src [by-hash=force] https://home-packages.chinauos.com/home plum main contrib non-free\n'
        elif (self.os_edition == self.os_edition_name[2]):
            return '## Generated by deepin-installer\n' \
                'deb [by-hash=force] https://home-packages.chinauos.com/home plum main contrib non-free\n' \
                '#deb-src [by-hash=force] https://home-packages.chinauos.com/home plum main contrib non-free\n'
        else:
            raise Exception('该脚本不适用当前操作系统')

def main():
    get_auth()
    src_default = DefaultSources()
    r1 = src_default.get_default_sources()
    r2 = src_default.default_sources_should_be()
    if (r1 != r2):
        if (user_agree_to_reset(src_default.src_sources_list)):
            src_default.reset_default_sources()
    else:
        msg="默认源" + src_default.src_sources_list + "正常，无需重置。"
        print(msg)

    # os.system('apt update -y && apt upgrade -y')
    input('按任意键退出')


if __name__ == '__main__':
    main()
